language: php
php:
  - "7.0"
services:
  - mysql
before_script:
  - "mysql -uroot -e 'create database IF NOT EXISTS `doc`;'"
  - "mysql -uroot doc -e 'source tests/doc.sql;'"
  - composer self-update
  - composer update